<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-LPKJ4V1" name="sfdcTests.ContactsTest" tests="8" failures="1" timestamp="10 Oct 2023 00:19:26 GMT" time="115.622" errors="0">
  <testcase name="CreateNewContact_TC25" time="13.203" classname="sfdcTests.ContactsTest"/>
  <testcase name="CreateNewView_TC26" time="8.606" classname="sfdcTests.ContactsTest"/>
  <testcase name="recentlyCreatedContact_TC27" time="11.701" classname="sfdcTests.ContactsTest"/>
  <testcase name="myContactView_TC28" time="8.740" classname="sfdcTests.ContactsTest"/>
  <testcase name="ViewContactName_TC29" time="47.486" classname="sfdcTests.ContactsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at sfdcTests.ContactsTest.ViewContactName_TC29(ContactsTest.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ViewContactName_TC29 -->
  <testcase name="createNewViewError_TC30" time="10.834" classname="sfdcTests.ContactsTest"/>
  <testcase name="cancelNewContact_TC31" time="7.728" classname="sfdcTests.ContactsTest"/>
  <testcase name="saveAndNewContact_TC32" time="7.324" classname="sfdcTests.ContactsTest"/>
</testsuite> <!-- sfdcTests.ContactsTest -->
